CREATE TABLE track
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    artist     VARCHAR(255),
    image_path VARCHAR(255),
    url        VARCHAR(255),
    you_tubeid VARCHAR(255),
    mbid       VARCHAR(255),
    lyrics     VARCHAR(255),
    CONSTRAINT pk_track PRIMARY KEY (id)
);

CREATE TABLE track_decade
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_trackdecade PRIMARY KEY (id)
);